// Code generated by TestWritePackParity. DO NOT EDIT.
//
// Regenerate with:
//
//	NIAC_PACK_PARITY_OUT=$PWD/internal/scenario/packs_parity.go \
//	  go test ./internal/scenario -run TestWritePackParity

package scenario

// packParity is the frozen authored truth every built-in pack pins. A pack
// reads its own row; nothing else may hold a second copy.
func packParity() map[string]Parity {
	return map[string]Parity{
		"hospital": {
			DeviceCount: 253, NetworkCount: 21, LinkCount: 278,
			DeviceNamesSHA256: "46c5b3aa53545f042b7dda398008dd8fa972b289e5fc29cc34dbb2cbf5d1715c",
			NetworksSHA256:    "6ea6e41e8bbd4c0ff83c09975f1bdee646231ecb89b8dc57fd15516ce5debb57",
			LinksSHA256:       "57b98c6eae8062f0451869556079cfd798b4322f5bb10769f277f154e94317a0",
			InterfacesSHA256:  "962538c057cedb309adb27cd1b5c699360eb998cfd50663585669993233fb0a0",
		},
		"warehouse": {
			DeviceCount: 264, NetworkCount: 12, LinkCount: 283,
			DeviceNamesSHA256: "23032acea2d0c4c0b285527b6d303cec45fff7fb44daf02fc63927f57cf39c0a",
			NetworksSHA256:    "4b45bbf256fb1440d30d2149f3691664404012f192d5f98f788bcc0c413e90b5",
			LinksSHA256:       "7ad5d8aaf4a18e03075921c1bd79b2bd22967f0af9673b10cd29e5742e9ca52f",
			InterfacesSHA256:  "386e77521b6070bfe23300402f15cff386cebb0042194a291c2806ba90d8bb72",
		},
		"campus": {
			DeviceCount: 255, NetworkCount: 39, LinkCount: 282,
			DeviceNamesSHA256: "9de0bebfd020e5456547385a2d09a9e6da08e57fbf192434f5997cb5f73c4e97",
			NetworksSHA256:    "7262a118fbb0f2d4977d02895b839d0cbce5fd1161201b0f27a5b37fc3eb72ce",
			LinksSHA256:       "1f3e01fac76bd1baff4ec76cbee9ae49b563aedc5cebb5d3e1fb53b9220b90f6",
			InterfacesSHA256:  "14ecc06b2b4ab0aadbda3b48eff863c63d67e3ae9624872c59d1bbc7d60e46a7",
		},
		"enterprise-scale": {
			DeviceCount: 543, NetworkCount: 39, LinkCount: 634,
			DeviceNamesSHA256: "dac6ff5f47442b977e1b69125ea7ea58f67635af8e7e2dd5efdb7ec084f5af45",
			NetworksSHA256:    "e879b7ba38e40f925809edc3bf98d2044959df5d2f76d492e6f2019cbcba5555",
			LinksSHA256:       "673a9d3da1c2144b7dd09e30ce1f0be07699509bf603eed83f29a0e915e6ec27",
			InterfacesSHA256:  "ee83891b1095692fb1942a472aab247123cda50d199f93198bc5594cd5b1d08a",
		},
		"retail": {
			DeviceCount: 253, NetworkCount: 21, LinkCount: 264,
			DeviceNamesSHA256: "7b64cff245e685919b5ecbf206d24fd4941bffd9029658132e0663330d4d18d1",
			NetworksSHA256:    "88cdfbd6e21a58552873afe83c93dac96b7fae0a28166ecb319475dbcc38d25b",
			LinksSHA256:       "a425fe68af250bd015ba61ad2939ffcc737fd41aa304f8adaaad4866a495b13d",
			InterfacesSHA256:  "1dcb1a19cc2ec09ea2eabd9128c21f0ddc17d918b694f15c56905e6a1e758f5b",
		},
		"manufacturing": {
			DeviceCount: 258, NetworkCount: 12, LinkCount: 264,
			DeviceNamesSHA256: "e092f94d35af3a26f660d7aa8020ef941f45738a83fddc762b56247759d327f6",
			NetworksSHA256:    "cc9ba550031f67fef5933891d5ff0dbd2aada452ba380493a2b52c830f25d0f8",
			LinksSHA256:       "367d7516d5261b8d7f2968d8a348febeb445805bc76a90602bfb1c804742b5af",
			InterfacesSHA256:  "d7dfd20816156f7494193f2e8cbe9526e8cee5e7a5b0c5fb4a1194cf702427f4",
		},
		"service-provider": {
			DeviceCount: 261, NetworkCount: 30, LinkCount: 281,
			DeviceNamesSHA256: "af3599453bf4293f456e793bd7222993bc48a253711a1d3bffde77e6bd56475b",
			NetworksSHA256:    "79fcb26f2a9f506a24540a583ae570b5c25e1dcf8a63ccfa21946b4912fc7720",
			LinksSHA256:       "dc523f6430c76542b6fc42a64bdc25f261b9116eb41daf17e7840f8a69e2990d",
			InterfacesSHA256:  "c8a880b6e77393e483bd762ccaea72559867e7ca75699c496407ecc5c1748c04",
		},
	}
}
