package scenario_test

import (
	"fmt"
	"os"
	"strings"
	"testing"

	"github.com/MustardSeedNetworks/niac-go/internal/scenario"
)

// TestWritePackParity regenerates the frozen parity table, and is skipped
// unless an operator asks for it by naming the destination:
//
//	NIAC_PACK_PARITY_OUT=$PWD/internal/scenario/packs_parity.go \
//	  go test ./internal/scenario -run TestWritePackParity
//
// It is the generator, not an assertion — TestEveryPackGeneratesWithoutYAMLRepair
// is what fails when a pack drifts. Re-signing used to mean copying six values
// per pack out of that failure by hand, into three places (the two pack files
// plus two tests that kept their own copy of the enterprise digests), which is
// four transcription opportunities per phase of work. Regenerate and commit
// instead, and read the diff: a digest that moved when nothing should have moved
// is the finding.
func TestWritePackParity(t *testing.T) {
	destination := os.Getenv("NIAC_PACK_PARITY_OUT")
	if destination == "" {
		t.Skip("set NIAC_PACK_PARITY_OUT to regenerate the pack parity table")
	}

	var out strings.Builder
	out.WriteString(`// Code generated by TestWritePackParity. DO NOT EDIT.
//
// Regenerate with:
//
//	NIAC_PACK_PARITY_OUT=$PWD/internal/scenario/packs_parity.go \
//	  go test ./internal/scenario -run TestWritePackParity

package scenario

// packParity is the frozen authored truth every built-in pack pins. A pack
// reads its own row; nothing else may hold a second copy.
func packParity() map[string]Parity {
	return map[string]Parity{
`)
	for _, pack := range scenario.Packs() {
		generated, err := scenario.Generate(pack.Request)
		if err != nil {
			t.Fatalf("generate %s: %v", pack.ID, err)
		}
		parity := generated.Manifest.Parity()
		fmt.Fprintf(&out, "\t\t%q: {\n", pack.ID)
		fmt.Fprintf(&out, "\t\t\tDeviceCount: %d, NetworkCount: %d, LinkCount: %d,\n",
			parity.DeviceCount, parity.NetworkCount, parity.LinkCount)
		fmt.Fprintf(&out, "\t\t\tDeviceNamesSHA256: %q,\n", parity.DeviceNamesSHA256)
		fmt.Fprintf(&out, "\t\t\tNetworksSHA256:    %q,\n", parity.NetworksSHA256)
		fmt.Fprintf(&out, "\t\t\tLinksSHA256:       %q,\n", parity.LinksSHA256)
		fmt.Fprintf(&out, "\t\t\tInterfacesSHA256:  %q,\n", parity.InterfacesSHA256)
		out.WriteString("\t\t},\n")
	}
	out.WriteString("\t}\n}\n")

	if err := os.WriteFile(destination, []byte(out.String()), 0o600); err != nil {
		t.Fatalf("write %s: %v", destination, err)
	}
}
