// Code generated by TestWritePackParity. DO NOT EDIT.
//
// Regenerate with:
//
//	NIAC_PACK_PARITY_OUT=$PWD/internal/scenario/packs_parity.go \
//	  go test ./internal/scenario -run TestWritePackParity

package scenario

// packParity is the frozen authored truth every built-in pack pins. A pack
// reads its own row; nothing else may hold a second copy.
func packParity() map[string]Parity {
	return map[string]Parity{
		"hospital": {
			DeviceCount: 253, NetworkCount: 21, LinkCount: 278,
			DeviceNamesSHA256: "46c5b3aa53545f042b7dda398008dd8fa972b289e5fc29cc34dbb2cbf5d1715c",
			NetworksSHA256:    "6ea6e41e8bbd4c0ff83c09975f1bdee646231ecb89b8dc57fd15516ce5debb57",
			LinksSHA256:       "57b98c6eae8062f0451869556079cfd798b4322f5bb10769f277f154e94317a0",
			InterfacesSHA256:  "962538c057cedb309adb27cd1b5c699360eb998cfd50663585669993233fb0a0",
		},
		"warehouse": {
			DeviceCount: 264, NetworkCount: 12, LinkCount: 283,
			DeviceNamesSHA256: "23032acea2d0c4c0b285527b6d303cec45fff7fb44daf02fc63927f57cf39c0a",
			NetworksSHA256:    "4b45bbf256fb1440d30d2149f3691664404012f192d5f98f788bcc0c413e90b5",
			LinksSHA256:       "7ad5d8aaf4a18e03075921c1bd79b2bd22967f0af9673b10cd29e5742e9ca52f",
			InterfacesSHA256:  "386e77521b6070bfe23300402f15cff386cebb0042194a291c2806ba90d8bb72",
		},
		"campus": {
			DeviceCount: 159, NetworkCount: 39, LinkCount: 186,
			DeviceNamesSHA256: "925de091b2a5dae9f15269407fcf8ee64583a4b244fd723af738d536ba67a344",
			NetworksSHA256:    "7262a118fbb0f2d4977d02895b839d0cbce5fd1161201b0f27a5b37fc3eb72ce",
			LinksSHA256:       "f7f09ed386d2cc5e1120eec231ef3351f4a0db4dfe29a6181ab84200633c1a16",
			InterfacesSHA256:  "cb2c196d2fc762f0eea9d8086985862369fa84d4ce8200d81013c15ae891efb9",
		},
		"enterprise-scale": {
			DeviceCount: 543, NetworkCount: 39, LinkCount: 634,
			DeviceNamesSHA256: "dac6ff5f47442b977e1b69125ea7ea58f67635af8e7e2dd5efdb7ec084f5af45",
			NetworksSHA256:    "e879b7ba38e40f925809edc3bf98d2044959df5d2f76d492e6f2019cbcba5555",
			LinksSHA256:       "673a9d3da1c2144b7dd09e30ce1f0be07699509bf603eed83f29a0e915e6ec27",
			InterfacesSHA256:  "ee83891b1095692fb1942a472aab247123cda50d199f93198bc5594cd5b1d08a",
		},
		"retail": {
			DeviceCount: 101, NetworkCount: 21, LinkCount: 112,
			DeviceNamesSHA256: "f35cb6d65b01776862b97e05d66081a1a26180c8163044c07ce65bdcd2dc9de0",
			NetworksSHA256:    "88cdfbd6e21a58552873afe83c93dac96b7fae0a28166ecb319475dbcc38d25b",
			LinksSHA256:       "72a5d4650aff90a0df4e173a530092ddcb6dc0410d17e1c66d65cba216c615ae",
			InterfacesSHA256:  "b154e068fff79644e8079b4ae96f8db0bd24d472ad0082d261204f2d65927899",
		},
		"manufacturing": {
			DeviceCount: 258, NetworkCount: 12, LinkCount: 264,
			DeviceNamesSHA256: "e092f94d35af3a26f660d7aa8020ef941f45738a83fddc762b56247759d327f6",
			NetworksSHA256:    "cc9ba550031f67fef5933891d5ff0dbd2aada452ba380493a2b52c830f25d0f8",
			LinksSHA256:       "367d7516d5261b8d7f2968d8a348febeb445805bc76a90602bfb1c804742b5af",
			InterfacesSHA256:  "d7dfd20816156f7494193f2e8cbe9526e8cee5e7a5b0c5fb4a1194cf702427f4",
		},
		"service-provider": {
			DeviceCount: 126, NetworkCount: 30, LinkCount: 146,
			DeviceNamesSHA256: "6872f0399e287bdf9814624a1f0bc2cd712fc510963cc7fea6f99dd85b8e8a6a",
			NetworksSHA256:    "79fcb26f2a9f506a24540a583ae570b5c25e1dcf8a63ccfa21946b4912fc7720",
			LinksSHA256:       "68d56459c7f0a910766b2d481e831ad4c7fb50532749ee18169e3c0a09421a7a",
			InterfacesSHA256:  "6678c6422a7a4b141a4ccd17cb51517e9be1c097228fde0759abacf417dab80c",
		},
	}
}
