// Code generated by TestWritePackParity. DO NOT EDIT.
//
// Regenerate with:
//
//	NIAC_PACK_PARITY_OUT=$PWD/internal/scenario/packs_parity.go \
//	  go test ./internal/scenario -run TestWritePackParity

package scenario

// packParity is the frozen authored truth every built-in pack pins. A pack
// reads its own row; nothing else may hold a second copy.
func packParity() map[string]Parity {
	return map[string]Parity{
		"hospital": {
			DeviceCount: 253, NetworkCount: 21, LinkCount: 278,
			DeviceNamesSHA256: "f507376680a8c8e38dc38d9120431eea0f4b02dfca9c647a8f6f7b1b6c27add8",
			NetworksSHA256:    "6ea6e41e8bbd4c0ff83c09975f1bdee646231ecb89b8dc57fd15516ce5debb57",
			LinksSHA256:       "990276a77f8ac0556de55a064acd29773e4d23ffcdd0402382a1f6717a516bfd",
			InterfacesSHA256:  "64263dafa48a2a118d958cf9bf17605221467bc9b0a4391af77adf50b8be2575",
		},
		"warehouse": {
			DeviceCount: 264, NetworkCount: 12, LinkCount: 283,
			DeviceNamesSHA256: "d82e13989d967f2130afafc7df176d073831cbdbf19c4257a0f8c10e361137bc",
			NetworksSHA256:    "4b45bbf256fb1440d30d2149f3691664404012f192d5f98f788bcc0c413e90b5",
			LinksSHA256:       "5a520369bcedcd6cc2f7a7581a7af956776fb93f666a57cabee761cebd465e38",
			InterfacesSHA256:  "5ab0690ad96f58ca08b459ed662e5f12d0170ef07062853503f9f0eeac021ac7",
		},
		"campus": {
			DeviceCount: 255, NetworkCount: 39, LinkCount: 282,
			DeviceNamesSHA256: "25dfc0c15cc61b518044901bffbf6881c2bba55d310cf36e83f2e5bc847c9154",
			NetworksSHA256:    "7262a118fbb0f2d4977d02895b839d0cbce5fd1161201b0f27a5b37fc3eb72ce",
			LinksSHA256:       "a7ca3fe58157671b0f0a4e1f8fbec1ce6b6e93c562e86e64a10df7b5caaa055f",
			InterfacesSHA256:  "ca81201ca6efa55173f7257e5797283b1cd5d4c64ab4018c30d4c8cb789cf54d",
		},
		"enterprise-scale": {
			DeviceCount: 543, NetworkCount: 39, LinkCount: 634,
			DeviceNamesSHA256: "a3bfdd8a3b22cdd30d1840b41c688bdd738cf8efefd391cc184a8583c9e3af3c",
			NetworksSHA256:    "e879b7ba38e40f925809edc3bf98d2044959df5d2f76d492e6f2019cbcba5555",
			LinksSHA256:       "eeb70623e55d70a0158c9801fee18fa43a62840b4e8c85ef10152dc149f89c28",
			InterfacesSHA256:  "0ddbcb8548cf20d8ad7fd9258713095af6a3281e21984467cbef63a43cb96fcb",
		},
		"retail": {
			DeviceCount: 253, NetworkCount: 21, LinkCount: 264,
			DeviceNamesSHA256: "e5ed3fc8a7883d92df91d6da33e024f2907e168eeded922df01006dd18b9dc7d",
			NetworksSHA256:    "88cdfbd6e21a58552873afe83c93dac96b7fae0a28166ecb319475dbcc38d25b",
			LinksSHA256:       "abd4def84ae9c91f8c08428af421a4c5adaa292c5816fee772573b1729419d0d",
			InterfacesSHA256:  "87caa5af536ca5a13371a5cc32098578677a7ccf67ac8c23605f1d41c6029879",
		},
		"manufacturing": {
			DeviceCount: 258, NetworkCount: 12, LinkCount: 264,
			DeviceNamesSHA256: "03b2b5b61055c0b0985f0e1e55909e92088cf34664a8e2e26c1a305b0f8f09ff",
			NetworksSHA256:    "cc9ba550031f67fef5933891d5ff0dbd2aada452ba380493a2b52c830f25d0f8",
			LinksSHA256:       "3a1f12c94b21efc17798dd83569de172df7ab1606cd1599b0b3cbd283900c0c9",
			InterfacesSHA256:  "b5fec4f6e4550b15460147cb02df716795a236965c9a6da13a7048d042665f4b",
		},
		"service-provider": {
			DeviceCount: 261, NetworkCount: 30, LinkCount: 281,
			DeviceNamesSHA256: "f3938f27fa788d9744698fdd6941236038571249a9a4d185c20346fc2ada0c24",
			NetworksSHA256:    "79fcb26f2a9f506a24540a583ae570b5c25e1dcf8a63ccfa21946b4912fc7720",
			LinksSHA256:       "3bd9510a40c5d768f331a0e3aa90558a906c0ec42f54066bcf889419e3004ea8",
			InterfacesSHA256:  "bbe5cc97ceb9bf089cb8e31c34833e69f8f7d9865ef63ed83f78e6ac3331e59c",
		},
	}
}
