package api

import (
	"crypto/sha256"
	"crypto/subtle"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"sync/atomic"
)

// TokenScope is a coarse permission level applied to bearer tokens.
//
// ScopeReadOnly permits safe (read-only) HTTP methods: GET, HEAD, OPTIONS,
// TRACE. ScopeReadWrite additionally permits state-changing methods:
// POST, PUT, PATCH, DELETE.
//
// Ordering matters: ScopeReadOnly < ScopeReadWrite so callers can compare
// the looked-up scope against the required scope with `<`.
type TokenScope int

const (
	// ScopeReadOnly is the lowest privilege level. Tokens with this scope
	// can read state but cannot mutate it.
	ScopeReadOnly TokenScope = iota
	// ScopeReadWrite grants full read + write privileges. Wave 1's single
	// NIAC_API_TOKEN env var maps to this scope for back-compat.
	ScopeReadWrite
	// ScopeAdmin grants ScopeReadWrite plus the right to perform
	// destructive whole-config operations like /api/v1/config/import
	// which replaces the entire device topology in one shot (#743).
	// Existing /api/v1/devices/{host} edits, configs/templates CRUD,
	// etc. stay at ScopeReadWrite because they're routine operator
	// actions, not topology-replacement events.
	ScopeAdmin
)

// String renders the scope in the canonical hyphenated form used in the
// token-file JSON schema.
func (s TokenScope) String() string {
	switch s {
	case ScopeReadOnly:
		return "read-only"
	case ScopeReadWrite:
		return "read-write"
	case ScopeAdmin:
		return "admin"
	default:
		return "unknown"
	}
}

// ScopedToken pairs a raw bearer token value with the scope it carries.
// Used as the input to NewTokenStore / TokenStore.Replace and as the
// decoded shape of one entry in the token-file JSON.
type ScopedToken struct {
	Value string
	Scope TokenScope
}

// tokenSnapshot is the immutable read-side view of the token store. The
// auth middleware reads it via atomic.Pointer so a concurrent Replace
// does not contend on the mutex on the hot path.
type tokenSnapshot struct {
	byHash map[[sha256.Size]byte]TokenScope
}

// TokenStore holds the active set of bearer tokens with their scopes.
//
// Concurrent-safe: reads via atomic.Pointer[tokenSnapshot] (lock-free on
// the auth hot path); writes serialize through mu and publish a new
// snapshot atomically. In-flight requests that already passed the auth
// check are unaffected by a Replace — they hold no reference to the
// store after the middleware returns.
//
// Tokens are stored as sha256 digests so the raw value never lives in
// the long-term process memory once the snapshot is built. sha256 is
// used (not Argon2id) because these are high-entropy random strings
// generated by the operator (e.g. `openssl rand -base64 32`), not
// passwords; a fast constant-time-comparable digest is the right tool.
type TokenStore struct {
	cur atomic.Pointer[tokenSnapshot]
	mu  sync.Mutex
}

// ErrTokenFileWorldReadable is returned when the configured token file
// has mode bits wider than 0o600. Loading is refused to avoid a token
// disclosure via other local users.
var ErrTokenFileWorldReadable = errors.New("token file has wider-than-0600 permissions; refusing to load")

// ErrInvalidTokenScope is returned when a token-file entry declares a
// scope value the daemon does not understand.
var ErrInvalidTokenScope = errors.New("invalid token scope")

// ErrEmptyTokenValue is returned when a token-file entry has an empty
// "value" field. An empty token would degrade the auth check to an
// always-pass branch, so we refuse to load.
var ErrEmptyTokenValue = errors.New("token value must be non-empty")

// NewTokenStore returns a store seeded with the provided tokens. Pass
// nil or an empty slice for an unauthenticated server (the auth
// middleware treats an empty store as "no auth configured", matching
// the Wave 1 NIAC_API_TOKEN-unset behaviour).
func NewTokenStore(initial []ScopedToken) *TokenStore {
	store := new(TokenStore)
	store.cur.Store(buildSnapshot(initial))
	return store
}

// buildSnapshot hashes every input token and returns the immutable
// snapshot the atomic pointer will publish. Empty input yields an
// empty (non-nil) map so Lookup does a single nil-map probe and exits.
func buildSnapshot(tokens []ScopedToken) *tokenSnapshot {
	snap := &tokenSnapshot{byHash: make(map[[sha256.Size]byte]TokenScope, len(tokens))}
	for _, tok := range tokens {
		if tok.Value == "" {
			// Defensive — Load() rejects this upstream, but NewTokenStore
			// is a public API that can be called directly so we mirror
			// the guard here. Skipping the entry is safer than panicking
			// in a constructor; the empty-token slot would silently make
			// auth accept everyone otherwise.
			continue
		}
		digest := sha256.Sum256([]byte(tok.Value))
		snap.byHash[digest] = tok.Scope
	}
	return snap
}

// Lookup returns the scope associated with the given bearer token, or
// false if the token is not recognised. The comparison is constant-time
// per-entry: for each known digest we compare against the request's
// digest with crypto/subtle so we do not leak which token matched via
// timing. With map indexing alone an attacker could measure hash-table
// hit/miss timing, so we iterate.
func (s *TokenStore) Lookup(token string) (TokenScope, bool) {
	snap := s.cur.Load()
	if snap == nil || len(snap.byHash) == 0 {
		return 0, false
	}
	clientDigest := sha256.Sum256([]byte(token))

	var (
		matched      bool
		matchedScope TokenScope
	)
	for serverDigest, scope := range snap.byHash {
		serverDigestCopy := serverDigest // re-bind for &-address safety inside the loop
		// ConstantTimeCompare returns 1 iff equal. We OR the result into
		// matched without short-circuiting so the loop always inspects
		// every entry. This is overkill at niac's token-count scale
		// (1-2 tokens) but keeps the semantics honest for the future.
		eq := subtle.ConstantTimeCompare(serverDigestCopy[:], clientDigest[:]) == 1
		if eq {
			matched = true
			matchedScope = scope
		}
	}
	return matchedScope, matched
}

// Len reports how many tokens are active. Used by SIGHUP logging and
// by the gate that decides whether auth is configured.
func (s *TokenStore) Len() int {
	snap := s.cur.Load()
	if snap == nil {
		return 0
	}
	return len(snap.byHash)
}

// ScopeCounts returns a breakdown of the active tokens by scope, used
//
// Returns (readOnly, readWrite, admin) counts. Admin tier (#743) is
// returned separately so dashboards can surface high-privilege token
// counts at a glance.
//
// Deprecated naming kept on the function returning three ints; callers
// should treat the third return as admin-token count.
// by the SIGHUP reload log line so operators see "rotated to N tokens
// (RO=X RW=Y)" without ever logging the values themselves.
func (s *TokenStore) ScopeCounts() (int, int, int) {
	snap := s.cur.Load()
	if snap == nil {
		return 0, 0, 0
	}
	var readOnly, readWrite, admin int
	for _, scope := range snap.byHash {
		switch scope {
		case ScopeReadOnly:
			readOnly++
		case ScopeReadWrite:
			readWrite++
		case ScopeAdmin:
			admin++
		}
	}
	return readOnly, readWrite, admin
}

// Replace atomically swaps the active token set. In-flight requests
// that already passed the auth check are unaffected; only NEW requests
// arriving after this call see the new tokens.
//
// The mutex serialises concurrent Replace callers; the atomic.Pointer
// publish makes the new snapshot visible to lock-free readers in a
// single store.
func (s *TokenStore) Replace(tokens []ScopedToken) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.cur.Store(buildSnapshot(tokens))
}

// tokenFileSchema is the on-disk JSON shape of a token file. The exact
// schema is documented in the daemon flag help and in the Wave 2 PR
// body: `{"tokens":[{"value":"...","scope":"read-only|read-write"}]}`.
type tokenFileSchema struct {
	Tokens []tokenFileEntry `json:"tokens"`
}

type tokenFileEntry struct {
	Value string `json:"value"`
	Scope string `json:"scope"`
}

// LoadTokenFile reads and validates a token JSON file from disk.
//
// File permissions must be exactly 0o600 or narrower. A wider mode
// (0o644, 0o666, ...) is treated as a configuration error and the
// function returns ErrTokenFileWorldReadable so the caller can keep
// the previous tokens active rather than swapping in a possibly-
// exposed file. Symlinks are followed by os.Stat — operators who want
// to lock that down can chmod the symlink target.
//
// The path is filepath.Clean()'d before any filesystem call so static
// analysers can see the input is sanitised. Operators choose the
// path via --token-file or NIAC_API_TOKEN_FILE, so a traversal-style
// argument is operator self-harm rather than an attack vector.
func LoadTokenFile(path string) ([]ScopedToken, error) {
	cleanPath := filepath.Clean(path)
	info, err := os.Stat(cleanPath)
	if err != nil {
		return nil, fmt.Errorf("stat token file %q: %w", cleanPath, err)
	}
	// 0o077 = "any bits set for group or other". The check tolerates
	// the owner-execute bit (0o100) since that would be unusual but
	// harmless on a regular file.
	if info.Mode().Perm()&0o077 != 0 {
		return nil, fmt.Errorf(
			"%w: %q has mode %o",
			ErrTokenFileWorldReadable,
			cleanPath,
			info.Mode().Perm(),
		)
	}
	raw, err := os.ReadFile(cleanPath)
	if err != nil {
		return nil, fmt.Errorf("read token file %q: %w", cleanPath, err)
	}
	var decoded tokenFileSchema
	if jsonErr := json.Unmarshal(raw, &decoded); jsonErr != nil {
		return nil, fmt.Errorf("parse token file %q: %w", cleanPath, jsonErr)
	}
	tokens := make([]ScopedToken, 0, len(decoded.Tokens))
	for i, entry := range decoded.Tokens {
		if entry.Value == "" {
			return nil, fmt.Errorf("token file %q entry %d: %w", cleanPath, i, ErrEmptyTokenValue)
		}
		scope, scopeErr := parseScope(entry.Scope)
		if scopeErr != nil {
			return nil, fmt.Errorf("token file %q entry %d: %w", cleanPath, i, scopeErr)
		}
		tokens = append(tokens, ScopedToken{Value: entry.Value, Scope: scope})
	}
	return tokens, nil
}

// parseScope normalises the JSON scope field to a TokenScope. Hyphen
// and underscore forms are both accepted because operators frequently
// transcribe the value by hand.
func parseScope(s string) (TokenScope, error) {
	switch strings.ToLower(strings.TrimSpace(s)) {
	case "read-only", "readonly", "read_only", "ro":
		return ScopeReadOnly, nil
	case "read-write", "readwrite", "read_write", "rw", "":
		// Empty defaults to read-write for back-compat with the Wave 1
		// single-token model — an operator hand-crafting the file who
		// forgets the scope key should get the safer, Wave-1-equivalent
		// behaviour rather than a load failure.
		return ScopeReadWrite, nil
	case "admin":
		return ScopeAdmin, nil
	default:
		return 0, fmt.Errorf("%w: %q", ErrInvalidTokenScope, s)
	}
}

// RequiredScopeForMethod returns the minimum scope needed to serve a
// request with the given HTTP method. Safe methods (GET/HEAD/OPTIONS/
// TRACE) require only ScopeReadOnly; state-changing methods require
// ScopeReadWrite. Unknown methods are treated as state-changing — the
// HTTP standard reserves the safety property to a known set, and a
// future custom verb arriving at niac should fail closed.
func RequiredScopeForMethod(method string) TokenScope {
	switch strings.ToUpper(method) {
	case "GET", "HEAD", "OPTIONS", "TRACE":
		return ScopeReadOnly
	default:
		return ScopeReadWrite
	}
}
