package walkmeta_test

import (
	"testing"

	"github.com/MustardSeedNetworks/niac-go/internal/walkmeta"
)

func TestParse(t *testing.T) {
	cases := []struct {
		name    string
		content string
		want    walkmeta.Provenance
	}{
		{"declared captured", "# Source: captured\n.1.3.6.1.2.1.1.5.0 = STRING: sw\n", walkmeta.Captured},
		{"declared generated", "# Source: generated\n.1.3.6.1.2.1.1.5.0 = STRING: sw\n", walkmeta.Generated},
		{
			"below other header lines",
			"# SNMP Walk File for Arista\n# Source: generated\n# Date: 2025-11-11\n.1.3.6.1.2.1.1.1.0 = STRING: x\n",
			walkmeta.Generated,
		},
		// One exact spelling, so the reader and the CI gate agree about what
		// counts as labelled.
		{"extra spacing is not the header", "#   Source:   captured\n.1.3.6 = STRING: x\n", walkmeta.Unknown},
		{"a capitalised value is not the header", "# Source: Captured\n.1.3.6 = STRING: x\n", walkmeta.Unknown},
		{"blank lines before the header", "\n\n# Source: captured\n.1.3.6 = STRING: x\n", walkmeta.Captured},
		{"no header at all", ".1.3.6.1.2.1.1.5.0 = STRING: sw\n", walkmeta.Unknown},
		{"a header that says nothing about source", "# Generated by something\n.1.3.6 = STRING: x\n", walkmeta.Unknown},
		{"an unrecognised value is not a provenance", "# Source: guessed\n.1.3.6 = STRING: x\n", walkmeta.Unknown},
		{"empty content", "", walkmeta.Unknown},
		{
			"a comment after the content starts is not a header",
			".1.3.6 = STRING: x\n# Source: captured\n",
			walkmeta.Unknown,
		},
	}

	for _, testCase := range cases {
		t.Run(testCase.name, func(t *testing.T) {
			if got := walkmeta.Parse([]byte(testCase.content)); got != testCase.want {
				t.Errorf("Parse() = %q, want %q", got, testCase.want)
			}
		})
	}
}

// TestParseStopsAtTheContent: a capture is megabytes of OIDs, and the header
// is the run of comments at the top. Parse must not scan the body.
func TestParseStopsAtTheContent(t *testing.T) {
	body := make([]byte, 0, 1<<16)
	for range 2000 {
		body = append(body, ".1.3.6.1.2.1.2.2.1.2.1 = STRING: eth0\n"...)
	}
	if got := walkmeta.Parse(body); got != walkmeta.Unknown {
		t.Errorf("Parse() = %q, want Unknown", got)
	}
}

func TestEnsureAddsTheHeaderOnlyWhenItIsMissing(t *testing.T) {
	plain := []byte(".1.3.6.1.2.1.1.5.0 = STRING: sw\n")
	stamped := walkmeta.Ensure(plain, walkmeta.Captured)
	if walkmeta.Parse(stamped) != walkmeta.Captured {
		t.Fatalf("Ensure did not stamp the header: %q", stamped)
	}
	if string(stamped[len(stamped)-len(plain):]) != string(plain) {
		t.Errorf("Ensure changed the content below the header: %q", stamped)
	}

	// Re-running a tool must not relabel what an earlier tool decided: a
	// generated walk put through the sanitizer stays generated.
	generated := []byte("# Source: generated\n.1.3.6 = STRING: x\n")
	if got := walkmeta.Ensure(generated, walkmeta.Captured); string(got) != string(generated) {
		t.Errorf("Ensure relabelled a declared walk: %q", got)
	}
}

func TestLineRoundTripsThroughParse(t *testing.T) {
	for _, provenance := range []walkmeta.Provenance{walkmeta.Captured, walkmeta.Generated} {
		content := walkmeta.Line(provenance) + "\n.1.3.6 = STRING: x\n"
		if got := walkmeta.Parse([]byte(content)); got != provenance {
			t.Errorf("Parse(Line(%q)) = %q", provenance, got)
		}
	}
}
