// niac-openapi generates docs/openapi.yaml from the capability registry in
// internal/api/route.go, so the published API description cannot drift from
// the routes the daemon actually serves.
//
// Usage:
//
//	niac-openapi [-source docs/openapi-source.yaml] [-o docs/openapi.yaml]
//
// The registry supplies every path, its methods and its policy — auth, CSRF,
// admin scope, rate limiting and the body cap — which is exactly the part a
// hand-written spec got wrong. Prose, path parameter names and bodies come
// from the source file. See docs/openapi-source.yaml for the split.
package main

import (
	"errors"
	"flag"
	"fmt"
	"maps"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/MustardSeedNetworks/niac-go/internal/api"
)

func main() {
	source := flag.String("source", "docs/openapi-source.yaml", "hand-written preamble and per-operation enrichment")
	out := flag.String("o", "", "output file path; '-' or empty writes to stdout")
	flag.Parse()

	sourceData, err := os.ReadFile(*source)
	if err != nil {
		fmt.Fprintf(os.Stderr, "niac-openapi: %v\n", err)
		os.Exit(1)
	}

	doc, err := generate(sourceData, api.RouteManifest())
	if err != nil {
		fmt.Fprintf(os.Stderr, "niac-openapi: %v\n", err)
		os.Exit(1)
	}

	if *out == "" || *out == "-" {
		if _, writeErr := os.Stdout.Write(doc); writeErr != nil {
			fmt.Fprintf(os.Stderr, "niac-openapi: %v\n", writeErr)
			os.Exit(1)
		}
		return
	}
	if writeErr := os.WriteFile(*out, doc, 0o600); writeErr != nil {
		fmt.Fprintf(os.Stderr, "niac-openapi: %v\n", writeErr)
		os.Exit(1)
	}
}

// pathItem is one OpenAPI path object: lower-cased method names mapping to
// operations, plus the shared "parameters" list. operation is one of those
// operations. Both stay map-shaped because that is what yaml.Marshal emits.
type (
	operation map[string]any
	pathItem  map[string]any
)

// sourceDoc is docs/openapi-source.yaml: the parts of the description the
// route registry cannot know.
type sourceDoc struct {
	// Preamble is copied verbatim to the top level of the output (info,
	// servers, tags, components…). `paths` is generated and is rejected here.
	Preamble map[string]any `yaml:"preamble"`
	// Operations enriches a generated operation, keyed "<METHOD> <path>"
	// with the registry's own path (a prefix route keeps its trailing "/").
	Operations map[string]operationSource `yaml:"operations"`
}

// operationSource is one enrichment entry. Everything except pathTemplate is
// merged onto the generated operation object.
type operationSource struct {
	// PathTemplate renames a Go 1.22 prefix route to its documented shape,
	// e.g. /api/v1/sessions/ -> /api/v1/sessions/{id}. Every method on one
	// path must agree, and the template's parameters are declared for it.
	PathTemplate string         `yaml:"pathTemplate"`
	Rest         map[string]any `yaml:",inline"`
}

// generate renders the OpenAPI document. Both inputs are explicit so the
// generator is testable without a file or a live server.
func generate(sourceData []byte, routes []api.RoutePolicy) ([]byte, error) {
	var src sourceDoc
	dec := yaml.NewDecoder(strings.NewReader(string(sourceData)))
	dec.KnownFields(true)
	if err := dec.Decode(&src); err != nil {
		return nil, fmt.Errorf("parsing source: %w", err)
	}
	if _, ok := src.Preamble["paths"]; ok {
		return nil, errors.New("source preamble must not define `paths`: it is generated from the registry")
	}

	paths, err := buildPaths(routes, src.Operations)
	if err != nil {
		return nil, err
	}

	doc := map[string]any{}
	maps.Copy(doc, src.Preamble)
	doc["paths"] = paths

	// The error envelope every route shares is the one DTO the registry
	// implies, so it is generated rather than restated.
	components, _ := doc["components"].(map[string]any)
	if components == nil {
		components = map[string]any{}
		doc["components"] = components
	}
	schemas, _ := components["schemas"].(map[string]any)
	if schemas == nil {
		schemas = map[string]any{}
		components["schemas"] = schemas
	}
	errSchema, err := errorSchema()
	if err != nil {
		return nil, err
	}
	schemas["Error"] = errSchema

	body, err := yaml.Marshal(doc)
	if err != nil {
		return nil, err
	}
	header := "# GENERATED by `make openapi` (cmd/niac-openapi) — do not edit.\n" +
		"# Paths and their policy come from the capability registry\n" +
		"# (internal/api/route.go); prose and bodies from docs/openapi-source.yaml.\n"
	return append([]byte(header), body...), nil
}

// unauthenticatedRoutes are registered directly in registerAPIRoutes rather
// than through the registry, because auth is what the registry applies and
// these two deliberately have none. They are real surface, so they are
// documented; check-route-policy.sh is what keeps the list from growing.
func unauthenticatedRoutes() []api.RoutePolicy {
	return []api.RoutePolicy{
		{Path: "/__version", Methods: []string{"GET"}},
		{Path: "/__capabilities", Methods: []string{"GET"}},
	}
}

// notFoundFallback is the registry's catch-all for unmatched /api requests.
// It accepts every method only so it can answer 404 in the daemon's JSON
// envelope rather than net/http's text; documenting it as seven operations
// would make a client generator emit seven methods for a 404.
const notFoundFallback = "/api/"

func buildPaths(routes []api.RoutePolicy, ops map[string]operationSource) (map[string]any, error) {
	public := unauthenticatedRoutes()
	all := make([]api.RoutePolicy, 0, len(routes)+len(public))
	all = append(all, public...)
	for _, rt := range routes {
		if rt.Path == notFoundFallback {
			continue
		}
		all = append(all, rt)
	}

	templates, err := resolveTemplates(all, ops)
	if err != nil {
		return nil, err
	}

	used := map[string]bool{}
	items := map[string]pathItem{}
	for _, rt := range all {
		docPath := templates[rt.Path]
		if docPath == "" {
			docPath = defaultTemplate(rt.Path)
		}
		item, ok := items[docPath]
		if !ok {
			item = pathItem{}
			items[docPath] = item
		}
		if params := pathParameters(docPath); len(params) > 0 {
			item["parameters"] = params
		}
		for _, m := range methodsOf(rt) {
			key := m + " " + rt.Path
			used[key] = true
			// Two registry routes resolving to one documented method would
			// silently drop an operation, which is worse than a wrong one.
			if _, clash := item[strings.ToLower(m)]; clash {
				return nil, fmt.Errorf("%s %s is claimed by more than one registered route (last: %s)",
					m, docPath, rt.Path)
			}
			item[strings.ToLower(m)] = merge(newOperation(rt, m, docPath), ops[key].Rest)
		}
	}

	if idErr := checkOperationIDs(items); idErr != nil {
		return nil, idErr
	}
	if staleErr := checkStale(ops, used); staleErr != nil {
		return nil, staleErr
	}

	paths := make(map[string]any, len(items))
	for docPath, item := range items {
		paths[docPath] = map[string]any(item)
	}
	return paths, nil
}

// merge lays the source enrichment over a generated operation. `responses` is
// merged a level deeper: the policy-derived 401/403/405/413/429 set is what
// the composed middleware actually returns, so a source entry adding a 200
// documents its body without discarding them. A source entry for a status the
// generator also produced wins, since only the source knows the body.
func merge(op operation, src map[string]any) operation {
	for k, v := range src {
		if k != "responses" {
			op[k] = v
			continue
		}
		srcResponses, isMap := v.(map[string]any)
		generated, hasGenerated := op["responses"].(map[string]any)
		if !isMap || !hasGenerated {
			op[k] = v
			continue
		}
		maps.Copy(generated, srcResponses)
	}
	return op
}

// resolveTemplates maps each registry path to the documented shape the source
// file gives it. Every method on one path must name the same one, or the
// document would claim two shapes for one route.
func resolveTemplates(all []api.RoutePolicy, ops map[string]operationSource) (map[string]string, error) {
	templates := map[string]string{}
	for _, rt := range all {
		for _, m := range methodsOf(rt) {
			src, ok := ops[m+" "+rt.Path]
			if !ok || src.PathTemplate == "" {
				continue
			}
			if prev, seen := templates[rt.Path]; seen && prev != src.PathTemplate {
				return nil, fmt.Errorf("%s: pathTemplate disagrees between methods (%q vs %q)",
					rt.Path, prev, src.PathTemplate)
			}
			templates[rt.Path] = src.PathTemplate
		}
	}
	return templates, nil
}

// checkOperationIDs rejects a duplicate id: it is invalid OpenAPI and
// generates colliding client methods, which is how the prefix routes went
// unnoticed before the documented template fed the id.
func checkOperationIDs(items map[string]pathItem) error {
	seen := map[string]string{}
	for docPath, item := range items {
		for method, value := range item {
			op, ok := value.(operation)
			if !ok {
				continue // "parameters"
			}
			id, _ := op["operationId"].(string)
			if prev, dup := seen[id]; dup {
				return fmt.Errorf("duplicate operationId %q: %s and %s %s", id, prev, method, docPath)
			}
			seen[id] = method + " " + docPath
		}
	}
	return nil
}

// checkStale rejects an enrichment entry for a route the registry does not
// serve — the failure mode a hand-written spec dies of.
func checkStale(ops map[string]operationSource, used map[string]bool) error {
	var stale []string
	for key := range ops {
		if !used[key] {
			stale = append(stale, key)
		}
	}
	if len(stale) == 0 {
		return nil
	}
	sort.Strings(stale)
	return fmt.Errorf("source operations name routes the registry does not serve: %s",
		strings.Join(stale, ", "))
}

// methodsOf returns the methods a route accepts. An empty registry `methods`
// means the handler dispatches for itself; the honest documentation of that
// is the full set the registry would otherwise gate.
func methodsOf(rt api.RoutePolicy) []string {
	if len(rt.Methods) > 0 {
		return rt.Methods
	}
	return []string{"GET", "POST", "PUT", "PATCH", "DELETE"}
}

// defaultTemplate documents a Go 1.22 prefix route (a path ending in "/")
// that the source file has not named. The trailing segment is real but
// unnamed, so it is documented as such rather than dropped.
func defaultTemplate(path string) string {
	if strings.HasSuffix(path, "/") && path != "/" {
		return path + "{subpath}"
	}
	return path
}

func pathParameters(docPath string) []any {
	var params []any
	for seg := range strings.SplitSeq(docPath, "/") {
		if !strings.HasPrefix(seg, "{") || !strings.HasSuffix(seg, "}") {
			continue
		}
		name := strings.Trim(seg, "{}")
		description := "Path parameter."
		if name == "subpath" {
			description = "Trailing path segment; this route matches by prefix."
		}
		params = append(params, map[string]any{
			"name":        name,
			"in":          "path",
			"required":    true,
			"description": description,
			"schema":      map[string]any{"type": "string"},
		})
	}
	return params
}

// operation renders what the registry knows about one method on one route.
// Every response listed here is one the composed middleware can actually
// return, which is the part the hand-written spec had wrong.
func newOperation(rt api.RoutePolicy, method, docPath string) operation {
	unauthenticated := rt.Path == "/__version" || rt.Path == "/__capabilities"

	responses := map[string]any{
		"500": errorResponse("Internal error."),
	}
	if !unauthenticated {
		responses["401"] = errorResponse("Missing or invalid bearer token.")
	}
	if rt.CSRF && !safeMethod(method) {
		responses["403"] = errorResponse("Missing or invalid CSRF token.")
	}
	if rt.Admin {
		responses["403"] = errorResponse("Admin scope required, or CSRF token missing or invalid.")
	}
	if rt.RateLimited {
		responses["429"] = errorResponse("Rate limit exceeded for this route class.")
	}
	if rt.MaxBodyBytes > 0 && !safeMethod(method) {
		responses["413"] = errorResponse(
			fmt.Sprintf("Request body larger than %d bytes.", rt.MaxBodyBytes))
	}
	if len(rt.Methods) > 0 {
		responses["405"] = errorResponse("Method not allowed; the Allow header lists the accepted set.")
	}

	op := operation{
		"operationId": operationID(docPath, method),
		"responses":   responses,
	}
	switch {
	case unauthenticated:
		op["security"] = []any{}
	case rt.CSRF && !safeMethod(method):
		op["security"] = []any{
			map[string]any{"BearerAuth": []any{}, "CsrfToken": []any{}},
		}
	}
	if rt.Admin {
		op["description"] = "Requires an admin-scoped token."
	}
	return op
}

func safeMethod(m string) bool { return m == "GET" || m == "HEAD" || m == "OPTIONS" }

func errorResponse(description string) map[string]any {
	return map[string]any{
		"description": description,
		"content": map[string]any{
			"application/json": map[string]any{
				"schema": map[string]any{"$ref": "#/components/schemas/Error"},
			},
		},
	}
}

// operationID builds a stable, unique id from the method and path so
// generated clients get usable names and the document diffs cleanly.
func operationID(path, method string) string {
	var id strings.Builder
	id.WriteString(strings.ToLower(method))
	for seg := range strings.SplitSeq(strings.Trim(path, "/"), "/") {
		seg = strings.Trim(seg, "{}")
		if seg == "" {
			continue
		}
		for _, part := range strings.FieldsFunc(seg, func(r rune) bool {
			return r == '-' || r == '_' || r == '.'
		}) {
			id.WriteString(strings.ToUpper(part[:1]))
			id.WriteString(part[1:])
		}
	}
	return id.String()
}
