package synth

import (
	"bytes"
	"fmt"
	"strings"
)

// DeviceInput is the subset of the niac device the synthesiser needs.
// Kept independent of internal/config.Device so tests can construct
// it cheaply and the package has no upstream import cycle with the
// config layer.
type DeviceInput struct {
	Hostname      string
	IP            string   // primary management IP — drives ipAddrTable
	AdditionalIPs []string // extra IPs from device.ips
	Community     string   // SNMP community; baked into sysContact comment
}

// BuildOptions tunes Build. Zero value uses the profile defaults.
type BuildOptions struct {
	// InterfaceCount overrides Profile.DefaultIfCount when > 0. The
	// design caps this server-side at 256 (well above any real-world
	// device) so a malicious payload can't blow up the walk file.
	InterfaceCount int
}

// MaxInterfaces is the upper bound for ifTable rows the synthesiser
// will emit regardless of the caller's request. Picked so even a
// fully-populated walk for the biggest type stays under a few KB.
const MaxInterfaces = 256

// Constants used by the various emit* helpers. Named so the mnd
// linter doesn't fire on each call site and so a reader can tell
// what an integer literal means without having to chase the SMI.
const (
	uptimeStub           = 100  // sysUpTime — 1 sec (timeticks are 1/100s)
	servicesL2           = 2    // sysServices: datalink only
	servicesL3           = 6    // sysServices: datalink + internet
	servicesL7           = 78   // sysServices: app/end-to-end/internet/datalink
	ifTypeEthernetCsmacd = 6    // IF-MIB ifType: ethernetCsmacd
	defaultMTU           = 1500 // ifMtu default
	ifStatusUp           = 1    // ifAdminStatus / ifOperStatus: up
	ipForwardingEnabled  = 1    // IP-MIB ipForwarding: forwarding(1)
	ipForwardingDisabled = 2    // IP-MIB ipForwarding: notForwarding(2)
	defaultIPTTL         = 64   // ipDefaultTTL
	dot1dBaseTypeTrans   = 2    // dot1dBaseType: transparent-only
	lldpChassisIDMAC     = 4    // lldpLocChassisIdSubtype: macAddress(4)
	lldpPortIDIfName     = 5    // lldpLocPortIdSubtype: interfaceName(5)
	mbpsToBps            = 1_000_000
)

// Build returns the synthesised walk file bytes for the device. The
// profile contains everything vendor-specific; the device input
// contributes the hostname/IPs that make the walk unique.
//
// Format matches what `snmpwalk -OnQ` produces (numeric OIDs, leading
// dot, quoted strings), so the simulator's existing walk parser
// handles the output without any special-casing.
func Build(p Profile, dev DeviceInput, opts BuildOptions) []byte {
	var buf bytes.Buffer

	emitHeader(&buf, p, dev)
	emitSystemGroup(&buf, p, dev)
	emitInterfaces(&buf, p, dev, opts)
	if p.IncludeIPMIB {
		emitIPMIB(&buf, p, dev)
	}
	if p.IncludeBridge {
		emitBridgeGroup(&buf, p)
	}
	if p.IncludeLLDP {
		emitLLDPMinimal(&buf, p, dev)
	}

	return buf.Bytes()
}

func emitHeader(buf *bytes.Buffer, p Profile, dev DeviceInput) {
	// Comment block at the top of the file. The walk parser ignores
	// lines starting with '#', so this serves as breadcrumbs for the
	// next operator who opens the file.
	fmt.Fprintf(buf, "# Synthesised baseline walk for %s (%s, %s).\n", dev.Hostname, p.Type, p.Vendor)
	fmt.Fprintf(buf, "# Generated by niac POST /api/v1/devices/%s/synthesize-walk.\n", dev.Hostname)
	fmt.Fprintln(buf, "# Edit freely; regeneration backs this file up to <name>.walk.bak.")
	fmt.Fprintln(buf)
}

func emitSystemGroup(buf *bytes.Buffer, p Profile, dev DeviceInput) {
	// 1.3.6.1.2.1.1.* — the SNMPv2-MIB system group every poller hits first.
	emitString(buf, "1.3.6.1.2.1.1.1.0", p.SysDescr)              // sysDescr
	emitOID(buf, "1.3.6.1.2.1.1.2.0", p.SysObjectID)              // sysObjectID
	emitTimeticks(buf, "1.3.6.1.2.1.1.3.0", uptimeStub)           // sysUpTime — 1 sec stub
	emitString(buf, "1.3.6.1.2.1.1.4.0", "niac-baseline-synth")   // sysContact
	emitString(buf, "1.3.6.1.2.1.1.5.0", dev.Hostname)            // sysName
	emitString(buf, "1.3.6.1.2.1.1.6.0", "synthesised by niac")   // sysLocation
	emitInteger(buf, "1.3.6.1.2.1.1.7.0", sysServicesFor(p.Type)) // sysServices
}

// sysServices is the bitmask of layers this device operates at.
// Bit 1=physical, 2=datalink, 4=internet, 8=end-to-end, 64=apps.
// Switches operate at L2 (2). Routers + firewalls at L3 (4+2=6).
// Hosts/servers/printers at L7 (64+8+4+2=78).
func sysServicesFor(t DeviceType) int {
	switch t {
	case TypeSwitch:
		return servicesL2
	case TypeRouter, TypeFirewall:
		return servicesL3
	case TypeAccessPoint, TypeVoIPPhone:
		return servicesL3
	case TypeHost, TypeServer, TypePrinter:
		return servicesL7
	default:
		return 0
	}
}

func emitInterfaces(buf *bytes.Buffer, p Profile, dev DeviceInput, opts BuildOptions) {
	count := opts.InterfaceCount
	if count <= 0 {
		count = p.DefaultIfCount
	}
	if count > MaxInterfaces {
		count = MaxInterfaces
	}
	if count < 1 {
		count = 1
	}

	// 1.3.6.1.2.1.2.* — IF-MIB.
	emitInteger(buf, "1.3.6.1.2.1.2.1.0", count) // ifNumber

	// ifTable (1.3.6.1.2.1.2.2.1.X.<ifIndex>) — emit each row of every
	// column for indices 1..count. Order: ifIndex, ifDescr, ifType,
	// ifMtu, ifSpeed, ifPhysAddress, ifAdminStatus, ifOperStatus.
	for i := 1; i <= count; i++ {
		base := "1.3.6.1.2.1.2.2.1"
		name := p.IfName(i)
		emitInteger(buf, fmt.Sprintf("%s.1.%d", base, i), i)                    // ifIndex
		emitString(buf, fmt.Sprintf("%s.2.%d", base, i), name)                  // ifDescr
		emitInteger(buf, fmt.Sprintf("%s.3.%d", base, i), ifTypeEthernetCsmacd) // ifType: ethernetCsmacd
		emitInteger(buf, fmt.Sprintf("%s.4.%d", base, i), defaultMTU)           // ifMtu
		// G115 waiver: p.IfSpeedMbps is a small literal in the profile
		// table (max 10_000) — the uint32 cast can't overflow.
		speedBps := uint32(p.IfSpeedMbps) * mbpsToBps //nolint:gosec // G115 — bounded by profile literals
		emitGauge32(buf, fmt.Sprintf("%s.5.%d", base, i), speedBps)
		emitPhysAddress(buf, fmt.Sprintf("%s.6.%d", base, i), syntheticMAC(dev.Hostname, i))
		emitInteger(buf, fmt.Sprintf("%s.7.%d", base, i), ifStatusUp) // ifAdminStatus: up
		emitInteger(buf, fmt.Sprintf("%s.8.%d", base, i), ifStatusUp) // ifOperStatus: up
		// Zero counters — the simulator's poller increments these as
		// traffic flows; we just need them present.
		emitCounter32(buf, fmt.Sprintf("%s.10.%d", base, i), 0) // ifInOctets
		emitCounter32(buf, fmt.Sprintf("%s.16.%d", base, i), 0) // ifOutOctets
	}
}

func emitIPMIB(buf *bytes.Buffer, p Profile, dev DeviceInput) {
	// 1.3.6.1.2.1.4.* — IP-MIB.
	// ipForwarding: 1 = forwarding, 2 = not-forwarding
	forwarding := ipForwardingDisabled
	if p.IPForwarding {
		forwarding = ipForwardingEnabled
	}
	emitInteger(buf, "1.3.6.1.2.1.4.1.0", forwarding)
	emitInteger(buf, "1.3.6.1.2.1.4.2.0", defaultIPTTL) // ipDefaultTTL

	// ipAddrTable (1.3.6.1.2.1.4.20.1.X.<ip>) — emit one row per
	// device IP. The index includes the IP itself per IP-MIB convention.
	ips := []string{}
	if dev.IP != "" {
		ips = append(ips, dev.IP)
	}
	ips = append(ips, dev.AdditionalIPs...)
	for idx, ip := range ips {
		base := "1.3.6.1.2.1.4.20.1"
		emitIPAddress(buf, fmt.Sprintf("%s.1.%s", base, ip), ip)           // ipAdEntAddr
		emitInteger(buf, fmt.Sprintf("%s.2.%s", base, ip), idx+1)          // ipAdEntIfIndex → wraps onto if 1
		emitString(buf, fmt.Sprintf("%s.3.%s", base, ip), "255.255.255.0") // ipAdEntNetMask
	}
}

func emitBridgeGroup(buf *bytes.Buffer, p Profile) {
	// 1.3.6.1.2.1.17.* — BRIDGE-MIB dot1dBase group. Minimal coverage:
	// just the base address + number of ports. The simulator's
	// BRIDGE-MIB module fills in the dynamic FDB at runtime.
	emitString(buf, "1.3.6.1.2.1.17.1.1.0", "00:00:00:00:00:00") // dot1dBaseBridgeAddress
	emitInteger(buf, "1.3.6.1.2.1.17.1.2.0", p.DefaultIfCount)   // dot1dBaseNumPorts
	emitInteger(buf, "1.3.6.1.2.1.17.1.3.0", dot1dBaseTypeTrans) // dot1dBaseType: transparent-only
}

func emitLLDPMinimal(buf *bytes.Buffer, _ Profile, dev DeviceInput) {
	// 1.0.8802.1.1.2.* — LLDP-MIB. Just the local-system group; the
	// runtime LLDP responder populates the remote table when peers
	// announce themselves.
	emitInteger(buf, "1.0.8802.1.1.2.1.3.1.0", lldpChassisIDMAC) // lldpLocChassisIdSubtype: macAddress
	emitString(buf, "1.0.8802.1.1.2.1.3.2.0", syntheticMAC(dev.Hostname, 1))
	emitInteger(buf, "1.0.8802.1.1.2.1.3.3.0", lldpPortIDIfName) // lldpLocPortIdSubtype: interfaceName
	emitString(buf, "1.0.8802.1.1.2.1.3.4.0", dev.Hostname)
}

// syntheticMAC derives a deterministic synthetic MAC from the
// hostname + interface index. Uses the locally-administered range
// (02:xx:xx:xx:xx:xx) so it can't collide with real hardware. Tests
// rely on the determinism — same input always yields the same MAC.
//
// gosec G115 waivers throughout: the byte() truncations of uint32
// shifts are the desired operation (we want one octet per position
// of the MAC). ifIndex is bounded ≤ MaxInterfaces (256) so the
// uint32 cast + the final byte() cast both fit cleanly.
func syntheticMAC(hostname string, ifIndex int) string {
	const (
		fnvOffsetBasis uint32 = 2166136261
		fnvPrime       uint32 = 16777619
		macByteMask    uint32 = 0xff
	)
	// Trivial FNV-1a fold over the hostname bytes — good enough for
	// "stable but different per host". Top byte fixed at 02 (locally
	// administered, unicast).
	h := fnvOffsetBasis
	for _, b := range []byte(hostname) {
		h ^= uint32(b)
		h *= fnvPrime
	}
	h += uint32(ifIndex) //nolint:gosec // G115 — ifIndex ≤ MaxInterfaces
	const (
		shift24 = 24
		shift16 = 16
		shift8  = 8
	)
	b1 := byte((h >> shift24) & macByteMask)
	b2 := byte((h >> shift16) & macByteMask)
	b3 := byte((h >> shift8) & macByteMask)
	b4 := byte(h & macByteMask)
	last := byte(uint32(ifIndex) & macByteMask) //nolint:gosec // G115 — ifIndex ≤ 256
	return strings.ToUpper(fmt.Sprintf("02:%02x:%02x:%02x:%02x:%02x", b1, b2, b3, b4, last))
}
